### ISSUE TITLE
cant build - linux 21.04 cpu

### ISSUE THREAD

**Issue by Dan70701** [Ledarium/rusty_pickaxe#5]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid length 17, expected a 0x-prefixed hex string with length of 40", line: 10, column: 36)', src/main.rs:125:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Ledarium** [comment]
It is literally written here that you need to insert your address https://github.com/Ledarium/rusty_pickaxe/blob/d09920cf1769787d79960d7034bd26d600628fd9/config.json#L10
Closing issue in favor of #3
