### ISSUE TITLE
error building in ubuntu 21.04 

### ISSUE THREAD

**Issue by ghost** [Ledarium/rusty_pickaxe#6]
cargo run --features cuda --release config.json

building it with. -> SM_86, compute_86
------  

 Compiling rusty_pickaxe v0.0.4 (/home/dnubuntu/downloads/git/denaro/rusty_pickaxe)
The following warnings were emitted during compilation:

warning: nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
warning: In file included from /usr/include/cuda_runtime.h:83,
warning:                  from <command-line>:
warning: /usr/include/crt/host_config.h:139:2: error: #error -- unsupported GNU version! gcc versions later than 10 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
warning:   139 | #error -- unsupported GNU version! gcc versions later than 10 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
warning:       |  ^~~~~

error: failed to run custom build command for `rusty_pickaxe v0.0.4 (/home/dnubuntu/downloads/git/denaro/rusty_pickaxe)`

Caused by:
  process didn't exit successfully: `/home/dnubuntu/downloads/git/denaro/rusty_pickaxe/target/release/build/rusty_pickaxe-def47e0ef59265f6/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  CXX_x86_64-unknown-linux-gnu = None
  CXX_x86_64_unknown_linux_gnu = None
  HOST_CXX = None
  CXX = None
  NVCC_x86_64-unknown-linux-gnu = None
  NVCC_x86_64_unknown_linux_gnu = None
  HOST_NVCC = None
  NVCC = None
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "nvcc" "-ccbin=c++" "-Xcompiler" "-O3" "-Xcompiler" "-ffunction-sections" "-Xcompiler" "-fdata-sections" "-Xcompiler" "-fPIC" "-m64" "-I" "./src" "-Xcompiler" "-Wall" "-Xcompiler" "-Wextra" "-cudart=shared" "-gencode" "arch=compute_50,code=sm_50" "-gencode" "arch=compute_52,code=sm_52" "-gencode" "arch=compute_60,code=sm_60" "-gencode" "arch=compute_61,code=sm_61" "-gencode" "arch=compute_75,code=sm_75" "-gencode" "arch=compute_86,code=sm_86" "-o" "/home/dnubuntu/downloads/git/denaro/rusty_pickaxe/target/release/build/rusty_pickaxe-6f5eb213ebf68f2a/out/./src/keccak.o" "-c" "./src/keccak.cu"
  cargo:warning=nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
  cargo:warning=In file included from /usr/include/cuda_runtime.h:83,
  cargo:warning=                 from <command-line>:
  cargo:warning=/usr/include/crt/host_config.h:139:2: error: #error -- unsupported GNU version! gcc versions later than 10 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
  cargo:warning=  139 | #error -- unsupported GNU version! gcc versions later than 10 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
  cargo:warning=      |  ^~~~~
  exit status: 1

  --- stderr

  error occurred: Command "nvcc" "-ccbin=c++" "-Xcompiler" "-O3" "-Xcompiler" "-ffunction-sections" "-Xcompiler" "-fdata-sections" "-Xcompiler" "-fPIC" "-m64" "-I" "./src" "-Xcompiler" "-Wall" "-Xcompiler" "-Wextra" "-cudart=shared" "-gencode" "arch=compute_50,code=sm_50" "-gencode" "arch=compute_52,code=sm_52" "-gencode" "arch=compute_60,code=sm_60" "-gencode" "arch=compute_61,code=sm_61" "-gencode" "arch=compute_75,code=sm_75" "-gencode" "arch=compute_86,code=sm_86" "-o" "/home/dnubuntu/downloads/git/denaro/rusty_pickaxe/target/release/build/rusty_pickaxe-6f5eb213ebf68f2a/out/./src/keccak.o" "-c" "./src/keccak.cu" with args "nvcc" did not execute successfully (status code exit status: 1).

**Comment by Ledarium** [comment]
```
unsupported GNU version! gcc versions later than 10 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
```
I guess you need to stick to `gcc-10` until shitvidia decides to update their sdk
